services:
  mysqldb:
    image: mysql:latest
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./database:/var/lib/mysql:rw
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: userdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet
  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    volumes:
      - ./nodeapp:/code
    ports:
      - 5000:5000
    expose:
      - 5000
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: 'letmein'
      DB_NAME: userdb
      DB_CONNECTION_LIMIT: 20
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      SERVER_PORT: 5000
    depends_on:
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge


